<?php

namespace App\Services\Ai;

class ToolActivityPresenter
{
    public function label(string $toolName): string
    {
        return match ($toolName) {
            'get_upcoming_schedule' => 'Membaca jadwal kuliah',
            'get_financial_summary' => 'Memeriksa ringkasan keuangan',
            'get_pending_tasks' => 'Memeriksa tugas yang belum selesai',
            'search_catatan' => 'Mencari catatan',
            'get_courses' => 'Membaca daftar mata kuliah',
            'get_academic_summary' => 'Memeriksa ringkasan akademik',
            'get_announcements' => 'Membaca pengumuman',
            'get_reminders' => 'Membaca reminder',
            'get_grade_scale' => 'Memeriksa skala nilai',
            'search_financial_transactions' => 'Mencari transaksi keuangan',
            'search_schedules' => 'Mencari jadwal',
            'search_tasks' => 'Mencari tugas',
            'get_workspace_overview' => 'Merangkum workspace',
            'export_workspace_summary' => 'Menyiapkan ringkasan workspace',
            'suggest_budget' => 'Menyusun saran anggaran',
            'suggest_study_plan' => 'Menyusun saran belajar',
            'check_schedule_conflicts' => 'Memeriksa bentrok jadwal',
            'find_free_time_slots' => 'Mencari waktu kosong',
            'preview_schedule_change' => 'Mempreview perubahan jadwal',
            'suggest_task_breakdown' => 'Menyusun pecahan tugas',
            'prepare_weekly_review' => 'Menyiapkan review mingguan',
            'detect_duplicate_records' => 'Mendeteksi data duplikat',
            'suggest_financial_anomalies' => 'Memeriksa anomali keuangan',
            'search_courses' => 'Mencari mata kuliah',
            'get_course_overview' => 'Merangkum mata kuliah',
            'compare_course_workload' => 'Membandingkan beban mata kuliah',
            'create_jadwal' => 'Menyiapkan perubahan jadwal',
            'create_keuangan' => 'Menyiapkan catatan keuangan',
            'create_tugas' => 'Menyiapkan tugas',
            'create_reminder' => 'Menyiapkan reminder',
            'create_course' => 'Menyiapkan mata kuliah',
            'create_kegiatan' => 'Menyiapkan kegiatan',
            'record_academic_result' => 'Menyiapkan hasil akademik',
            'manage_todolist' => 'Menyiapkan perubahan to-do',
            'manage_tugas' => 'Menyiapkan perubahan tugas',
            'update_catatan' => 'Menyiapkan perubahan catatan',
            'set_finance_budget' => 'Menyiapkan anggaran keuangan',
            'update_jadwal' => 'Menyiapkan pembaruan jadwal',
            'update_kegiatan' => 'Menyiapkan pembaruan kegiatan',
            'update_reminder' => 'Menyiapkan pembaruan reminder',
            'snooze_reminder' => 'Menyiapkan penundaan reminder',
            'update_keuangan' => 'Menyiapkan pembaruan transaksi',
            'update_course' => 'Menyiapkan pembaruan mata kuliah',
            'update_tugas' => 'Menyiapkan pembaruan tugas',
            'mark_announcement_read' => 'Menyiapkan status pengumuman',
            'duplicate_schedule' => 'Menyiapkan salinan jadwal',
            'copy_course_to_semester' => 'Menyiapkan salinan mata kuliah',
            'archive_note' => 'Menyiapkan arsip catatan',
            'restore_note' => 'Menyiapkan pemulihan catatan',
            'delegate_code_generation' => 'Mendelegasikan ke agen coding',
            'create_todolist' => 'Menyiapkan item to-do',
            'create_catatan' => 'Menyiapkan catatan',
            default => 'Menggunakan alat bantu',
        };
    }
}
